[package]
name = "dedma"
version = "0.1.2"
edition = "2021"

[dependencies]
sqlx = {version = "0.8", features = ["runtime-tokio","tls-native-tls","sqlite"]}
futures = "0.3"
tokio = {version = "1.39.2", features=["macros","rt"]}
anyhow = "1.0"
indicatif = "0.17.8"
